#!/usr/bin/env python3
# This script generates test_melty2_seeder.h

table = [
    0b011010,
    0b101001,
    0b011001,
    0b110001,
    0b001101,
    0b101100,
    0b011100,
    0b110100,
    0b001011,
    0b100011,
    0b010011,
    0b110010,
    0b001110,
    0b100110,
    0b010110,
    0b100101,
]


def check_table(tbl):
    if len(tbl) != 16:
        raise ValueError("table length must be 16")
    for v in tbl:
        if not 0 <= v < 64:
            raise ValueError("each table value must be in [0, 64)")
        if not v.bit_count != 3:
            raise ValueError("each table value must has three 1-bit")


check_table(table)


def check_seed(seed):
    if len(seed) != 4:
        raise ValueError("seed length must be 4")
    for s in seed:
        if not 0 <= s < 2 ** 32:
            raise ValueError("each seed value must be in [0, 2**32)")


def gen_key(seed):
    check_seed(seed)
    shift = 0
    key = 0
    for s in seed:
        for r in range(0, 32, 4):
            key |= table[s >> r & 0xff] << shift
            shift += 6
    return [key >> r & 0xffffffff for r in range(0, 192, 32)]


def gen_tests(f):
    cases = [
        [0, 0, 0, 0],
        [1, 2, 3, 4],
    ]

    def to_literal(ary):
        return "{" + ", ".join("UINT32_C(0x{:08x})".format(v) for v in ary) + "}"

    f.write('typedef struct {\n')
    f.write('    uint32_t seed[4];\n')
    f.write('    uint32_t key[6];\n')
    f.write('} TestCase;\n')
    f.write('\n')
    f.write('static const TestCase test_cases[] = {\n')
    for seed in cases:
        f.write(f"    {{{to_literal(seed)},\n")
        f.write(f"     {to_literal(gen_key(seed))}}},\n")
    f.write('};\n')


if __name__ == '__main__':
    with open('test_melty2_seeder.h', 'w') as f:
        f.write('/* This file is generated by gen_test_melty2_seeder.py */\n')
        f.write('\n')
        gen_tests(f)
