#!/usr/bin/env python3
# This script generates test_melty2_init.h

import binascii
import struct


def compute_crc32(seed):
    return binascii.crc32(struct.pack("<4L", *seed))


code5b6b_tbl = [
    [0x27, 0x18],
    [0x1d, 0x22],
    [0x2d, 0x12],
    [0x31, 0x31],
    [0x35, 0x0a],
    [0x29, 0x29],
    [0x19, 0x19],
    [0x38, 0x07],
    [0x39, 0x06],
    [0x25, 0x25],
    [0x15, 0x15],
    [0x34, 0x34],
    [0x0d, 0x0d],
    [0x2c, 0x2c],
    [0x1c, 0x1c],
    [0x17, 0x28],
    [0x1b, 0x24],
    [0x23, 0x23],
    [0x13, 0x13],
    [0x32, 0x32],
    [0x0b, 0x0b],
    [0x2a, 0x2a],
    [0x1a, 0x1a],
    [0x3a, 0x05],
    [0x33, 0x0c],
    [0x26, 0x26],
    [0x16, 0x16],
    [0x36, 0x09],
    [0x0e, 0x0e],
    [0x2e, 0x11],
    [0x1e, 0x21],
    [0x2b, 0x14],
]


def check_table(tbl):
    if len(tbl) != 32:
        raise ValueError("table length must be 32")
    for p, n in tbl:
        if not (2 <= n.bit_count() <= p.bit_count() and p.bit_count() + n.bit_count() == 6):
            raise ValueError("invalid bitcount")


check_table(code5b6b_tbl)


def check_seed(seed):
    if len(seed) != 4:
        raise ValueError("seed length must be 4")
    for s in seed:
        if not 0 <= s < 2 ** 32:
            raise ValueError("each seed value must be in [0, 2**32)")


def gen_key(seed):
    check_seed(seed)
    c = compute_crc32(seed)
    seed = ''.join('{:032b}'.format(s)[::-1] for s in seed)
    c = '{:032b}'.format(c)[::-1]
    is_positive = False
    tmp = []
    for i in range(32):
        n = seed[4*i:4*(i+1)] + c[i:i+1] 
        n = int(n[::-1], 2)
        codes = code5b6b_tbl[n]
        code = codes[0 if is_positive else 1]
        code_alt = codes[1 if is_positive else 0]
        if code != code_alt:
            is_positive = not is_positive
        tmp.append('{:06b}'.format(code)[::-1])
    key = ''.join(tmp)
    return [int(key[32*i:32*(i+1)][::-1], 2) for i in range(6)]


def gen_tests(f):
    cases = [
        [0, 0, 0, 0],
        [1, 2, 3, 4],
        [3141592653, 2718281828, 0x67452301, 0xefcdab89],
    ]

    def to_literal(ary):
        return "{" + ", ".join("UINT32_C(0x{:08x})".format(v) for v in ary) + "}"

    f.write("typedef struct {\n")
    f.write("    uint32_t seed[4];\n")
    f.write("    uint32_t key[6];\n")
    f.write("} TestCase;\n")
    f.write("\n")
    f.write("static const TestCase test_cases[] = {\n")
    for seed in cases:
        f.write(f"    {{{to_literal(seed)},\n")
        f.write(f"     {to_literal(gen_key(seed))}}},\n")
    f.write("};\n")


if __name__ == "__main__":
    with open("test_melty2_init.h", "w") as f:
        f.write("/* This file is generated by gen_test_melty2_init.py */\n")
        f.write("\n")
        gen_tests(f)
