/* This file is generated by gen_test_melty2_seeder.py */

typedef struct {
    uint32_t seed[4];
    uint32_t key[6];
} TestCase;

static const TestCase test_cases[] = {
    {{UINT32_C(0x00000000), UINT32_C(0x00000000), UINT32_C(0x00000000), UINT32_C(0x00000000)},
     {UINT32_C(0x9a69a69a), UINT32_C(0xa69a69a6), UINT32_C(0x69a69a69), UINT32_C(0x9a69a69a), UINT32_C(0xa69a69a6), UINT32_C(0x69a69a69)}},
    {{UINT32_C(0x00000001), UINT32_C(0x00000002), UINT32_C(0x00000003), UINT32_C(0x00000004)},
     {UINT32_C(0x9a69a6a9), UINT32_C(0xa69969a6), UINT32_C(0x69a69a69), UINT32_C(0x9a69a6b1), UINT32_C(0xa68d69a6), UINT32_C(0x69a69a69)}},
};
