/* This file is generated by gen_test_melty2_init.py */

typedef struct {
    uint32_t seed[4];
    uint32_t key[6];
} TestCase;

static const TestCase test_cases[] = {
    {{UINT32_C(0x00000000), UINT32_C(0x00000000), UINT32_C(0x00000000), UINT32_C(0x00000000)},
     {UINT32_C(0x8bb4b48b), UINT32_C(0x22d3e4b4), UINT32_C(0xe4b4b58d), UINT32_C(0xd3cc62d3), UINT32_C(0x31b58d22), UINT32_C(0x8d33392d)}},
    {{UINT32_C(0x00000001), UINT32_C(0x00000002), UINT32_C(0x00000003), UINT32_C(0x00000004)},
     {UINT32_C(0x392d3326), UINT32_C(0xbb598d33), UINT32_C(0x4cce4b48), UINT32_C(0x627634ba), UINT32_C(0x330ee4a7), UINT32_C(0x8d22ed2d)}},
    {{UINT32_C(0xbb40e64d), UINT32_C(0xa205b064), UINT32_C(0x67452301), UINT32_C(0xefcdab89)},
     {UINT32_C(0xad58a6d4), UINT32_C(0x94a9555a), UINT32_C(0x7324a39b), UINT32_C(0xac6a3ce5), UINT32_C(0x89732d43), UINT32_C(0xad12eab6)}},
};
