/* This file is generated by gen_seeder_tests.py */

static void test_empty(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_initkey(seeder, key);
}

static void test_null(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_null(seeder);
    melty2_initkey(seeder, key);
}

static void test_0(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(0));
    melty2_initkey(seeder, key);
}

static void test_1(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(1));
    melty2_initkey(seeder, key);
}

static void test_127(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(127));
    melty2_initkey(seeder, key);
}

static void test_128(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(128));
    melty2_initkey(seeder, key);
}

static void test_255(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(255));
    melty2_initkey(seeder, key);
}

static void test_256(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(256));
    melty2_initkey(seeder, key);
}

static void test_12345(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(12345));
    melty2_initkey(seeder, key);
}

static void test_65535(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(65535));
    melty2_initkey(seeder, key);
}

static void test_65536(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(65536));
    melty2_initkey(seeder, key);
}

static void test_pi_10d(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(3141592653));
    melty2_initkey(seeder, key);
}

static void test_2to32m1(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(4294967295));
    melty2_initkey(seeder, key);
}

static void test_2to32(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(4294967296));
    melty2_initkey(seeder, key);
}

static void test_sqrt2_10d_pi_10d(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(14142135623141592653));
    melty2_initkey(seeder, key);
}

static void test_2to64m1(melty2_key *key) {
    melty2_seeder seeder[1];
    melty2_initseeder(seeder);
    melty2_seed_uint(seeder, UINT64_C(18446744073709551615));
    melty2_initkey(seeder, key);
}

typedef struct {
    const char* name;
    void (*fn)(melty2_key *key);
    const char* expected_hex;
} TestCase;

static const TestCase test_cases[] = {
    {"test_empty", test_empty,
     "786a02f742015903c6c6fd852552d272912f4740e1584761"},
    {"test_null", test_null,
     "63b306835317e1a8c24e4d481289a0d48aa5699b0d6d5ccd"},
    {"test_0", test_0,
     "2fa3f686df876995167e7c2e5d74c4c7b6e48f8068fe0e44"},
    {"test_1", test_1,
     "9545ba37b230d8a2e716c4707586542780815b7c4088edcb"},
    {"test_127", test_127,
     "e92b41dd767e71d505805bcb09c6fdb3f0954b37b06e9cd7"},
    {"test_128", test_128,
     "5aeff8431522935d5e31f44be0d5f2854ba158a83b67065c"},
    {"test_255", test_255,
     "64528de49dcdd7cebe1b7f2b18372332255d67c598b45c0f"},
    {"test_256", test_256,
     "e4451e07b45a3431d251c689320258606092e3fb861954a2"},
    {"test_12345", test_12345,
     "08ebd3d2c85d2b9af6eb33b75d16266583336dfae779cde3"},
    {"test_65535", test_65535,
     "8bbca3bc2cb94a4ea061e42bc0060b0849ff7426bd7c3168"},
    {"test_65536", test_65536,
     "9f98b0f8307963aa34f3272102e5b69b72c23510c36803e8"},
    {"test_pi_10d", test_pi_10d,
     "1b9e63e491215e9bb96502b8d55728e31d7686b049c7b3a2"},
    {"test_2to32m1", test_2to32m1,
     "9fd5bfca3617be2aeaf36aac1aaec1d19016015ce4ee7fea"},
    {"test_2to32", test_2to32,
     "bcd981776095b3757a106f95936514c0dd481824752b591a"},
    {"test_sqrt2_10d_pi_10d", test_sqrt2_10d_pi_10d,
     "3aecdca6aebafcc34bbbf894652f35b33cbd2043ece692d1"},
    {"test_2to64m1", test_2to64m1,
     "011dd784631c27d6d93316319cf1e40f242c6b3b62a856fa"},
};
