/* This file is generated by gen_test_melty2_init.py */

typedef struct {
    uint32_t seed[4];
    uint32_t key[6];
} TestCase;

static const TestCase test_cases[] = {
    {{UINT32_C(0x00000000), UINT32_C(0x00000000), UINT32_C(0x00000000), UINT32_C(0x00000000)},
     {UINT32_C(0xca9ca9ca), UINT32_C(0x8d529ca9), UINT32_C(0x9ca9d875), UINT32_C(0x52e58d52), UINT32_C(0x29d8758d), UINT32_C(0x752e58d5)}},
    {{UINT32_C(0x00000001), UINT32_C(0x00000002), UINT32_C(0x00000003), UINT32_C(0x00000004)},
     {UINT32_C(0x58d52e4c), UINT32_C(0xa9e4752e), UINT32_C(0xb469ca9c), UINT32_C(0x2761d60e), UINT32_C(0x2e556276), UINT32_C(0x758d58d5)}},
    {{UINT32_C(0xbb40e64d), UINT32_C(0xa205b064), UINT32_C(0x67452301), UINT32_C(0xefcdab89)},
     {UINT32_C(0x67173a45), UINT32_C(0x78c669a9), UINT32_C(0x4e99eca2), UINT32_C(0x532dce64), UINT32_C(0x66f25895), UINT32_C(0x46b721a5)}},
};
